version: "3.8"

services:
  web:
    image: web_image
    container_name: web_container
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - WATCHPACK_POLLING=true
      # - CHOKIDAR_USEPOLLING=true
